### PR TITLE
fix: merge all options from vue.config

### LINKED ISSUE #25: Allow to use without RouterLayout
The following code:

```ts
import Vue from "vue"
import routes from "vue-auto-routing"
import VueRouter from "vue-router"

Vue.use(VueRouter)

const router = new VueRouter({
	mode: "history",
	base: process.env.BASE_URL,
	routes,
})

export default router
```

emits this warning:

```
[vue-router] Non-nested routes must include a leading slash character. Fix the following routes: 
```

Is there an elegant way to have vue-auto-routing emit non-nested routes, e.g. with a certain webpack loader option? Note that I'm deliberately avoiding the layouts plugin (which surfaced this unwanted coupling between the modules).

For now, I'm using this:

```ts
const router = new VueRouter({
	mode: "history",
	base: process.env.BASE_URL,
	routes: routes.map(route => ({ ...route, path: "/" + route.path })),
})
```

### PR DESCRIPTION
**Pull request by IlyaSemenov**
Merge all options from vue.config.js, not only `chunkNamePrefix`. Fixes #25.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,16 +1,14 @@
...
+module.exports = (api, options) => {
   const pluginOptions = {
-    pages: 'src/pages',
-    nested: true
-  }
-
-  if (opts.chunkNamePrefix != null) {
-    pluginOptions.chunkNamePrefix = opts.chunkNamePrefix
+    ...defaultOptions,
+    ...(options.pluginOptions && options.pluginOptions.autoRouting),
```
Comment (ktsn) [inline index.js:11]:
```suggestion
    ...((options.pluginOptions && options.pluginOptions.autoRouting) || {}),
```

**Review by ktsn — CHANGES_REQUESTED** [review]

File: index.js (hunk 1 above)
Comment (IlyaSemenov) [reply index.js:11]: Not sure what does this solve? `undefined` is a valid argument for the object rest operator.

If it were the Typescript code, it could be even more concise with `...options.pluginOptions?.autoRouting`.

Comment (ktsn) [reply index.js:11]: Oh, I misunderstood the behavior! Let's go with the current code, then.

**Review by ktsn — APPROVED** [review]
Thank you!
